### ISSUE TITLE
Windowed mode isn't 640x480

### ISSUE THREAD

**Issue by IlDucci** [p1pkin/demul#357]
This one was left from the last stable version: Every time I use the windowed mode, the 640x480 windows is rendered as 640x478-477.

What steps will reproduce the problem?
1.: Load Demul with any game or BIOS.
2.: Start the emulation in Windowed mode, at 640x480.
3.: Measure the screen (On the 12/22/15 alpha, see that the upper and lower areas are not crystal-clear, but a bit smoothed)

What is the expected output?
Windowed screen at 640x480, crystal-clear upper and lower areas like in Full Screen mode.

What do you see instead?
1 pixel wide, 2-4 lines not being drawn (Previous alphas) slightly distorted screen (12/22/15 alpha).

**Comment by p1pkin** [comment]
well,  that's because Naomi/Dreamcast have flexible video system, it is not hardcoded to exactly 480 lines, but can be any value instead, so games set display to whatever size whey want.
usually slightly less than 480 lines or slightly more. so in fact, in previous versions you have 'solid filled' 640x480 window because of inaccurate emulation of DC/Naomi video system and lack of keeping original aspect ratio.
is it a problem ?

**Comment by IlDucci** [comment]
So this should be normal? See how "Pausa" and "Volver al menú principal" look like. It's really a minor issue, but I want to be certain. 
![bugsof](https://cloud.githubusercontent.com/assets/5641681/12004243/60c07f60-ab49-11e5-931d-242242a7077f.png)

**Comment by p1pkin** [comment]
I'm not sure that's wrong here, but it looks you noticed how works bilinear interpolation. it can be disabled in options if you didn't like it (Linear filtering)

**Comment by IlDucci** [comment]
So, from the last alpha, the screen is rendered with bilinear interpolation? I was confused because it seemed in Shenmue that, on windowed mode, the internal resolution was 640x478, but on full screen it was 640x480.

If that's the normal way to do things, then please close this ticket.

**Comment by p1pkin** [comment]
ok then.
