### ISSUE TITLE
Fix for Sound distortion using new Plugin (and old), add: sync/skip or any other audio option.

### ISSUE THREAD

**Issue by Nashismo** [p1pkin/demul#363]
I have been using the newest Demul and the Emulation is really beautiful, but the sound is really terrible. My PC is:
GPU Nvidia 660Ti
i5 2400 3.3ghz
Windows 7.

I use 1x scale resolution and I get a constant 60fps the entire time and yet I still get these ugly sound distortions all the time, specially using the new Plugin for DX11. I also get distortion in the old DX11 plugin, but it's a bit less.

I have heard many people complain about this on the forums, so it is not only me. This issue is real and I think we would all love to have some more options for sound emulation.

Such as: Audio Synch
               Time Stretching Audio
               Or my favorite and easier (hopefully): Audio Skip.

**Comment by p1pkin** [comment]
I doubt it related to emulation at all, you are first user with such issue.
it looks more like some incompatibilities with your sound card or drivers.
so I can't reproduce this issue => its impossible to fix issues which I don't have.

**Comment by Nashismo** [comment]
Using the old DX11 plugin is not so strong, on the new one is "really" noticeable. All in all, couldn't there be an "option" for audio synch or Audio Skip?

Options are always good :) So we can fiddle around and test on our own?

I come from a different forum, Shenmue forums and there, many people have this issue.

Also VMU on fullscreen would be great! Thanks mate and congratulations, this emulator really has amazed me! Everyone is in awe I think, if not, they don't know nothing!

**Comment by p1pkin** [comment]
if its most notable on "new" DX11 I think I know that's the problem - it is faster than "old" one and produces significantly less GPU load. as result your graphics card drivers thinks 2D clock will be enough for this application and drop it down, but in fact its far not enough so in result you got slowdowns = audio distortion.

it's not big problem in the case of NVidia - there just needed create Demul profile in driver settings, and set there "Maximum performance" and "disable power saving" settings.
in the case of ATI/AMD it's more complicated, some tips I think can be located there - https://forums.dolphin-emu.org/Thread-unofficial-amd-ati-gpu-performance-guide-feat-dolphin

about sound - in fact Demul have "Stretching Audio" feature.
and no, "Skip Sound" or "Disable Sync" is not possible, because all hardware components including sound generation emulated like a single clockwork mechanism, so skipping or out of sync something will broke whole thing at all.

**Comment by Nashismo** [comment]
Thank you for answering p1pkin. I have found that when going from fullscreen to window screen is what creates sound distortion, then it stays distorted. Also, is it normal to see interlaced lines in the screen when using TV mode (480i) on the new DX11 plugin? I can only use VGA (480p) on the new DX11. It seems like the Emulator its so accurate now, that it needs to be displayed at its original resolution.
Fullscreen resolution option could be a nice addition! :) Or maybe a line in the .ini is all it takes?

Thank you again, thank you for your time and effort.

**Comment by p1pkin** [comment]
>  I have found that when going from fullscreen to window screen is what creates sound distortion

in such case this clearly related to graphics card drivers bugs mentioned above.

>  Also, is it normal to see interlaced lines in the screen when using TV mode (480i) on the new DX11 plugin?

ATM its normal. some more advanced de-interlace needed to be implemented.

> Fullscreen resolution option could be a nice addition! :) Or maybe a line in the .ini is all it takes?

that is benefits of this ? most users have LCD displays these days, so any resolution except native one does not make any sense.
