### ISSUE TITLE
Sound warped when fps drops

### ISSUE THREAD

**Issue by RinMaru** [p1pkin/demul#382]
Anytime the framerate drops the sound gets extremely warped and out of pitch. do you plan on improving the audio plugin?

**Comment by p1pkin** [comment]
short answer - no.
long answer - in Demul whole system emulated as single clockwork, there no hacks to make some "cogwheels" like sound emulation spinning while others is stuck because of luck of PC power to emulate whole thing at full speed. and I have no will to add such or any other hacks in future.

**Comment by RinMaru** [comment]
alright good thing im upgrading lol thanks
