### ISSUE TITLE
Dynamite Cop Input Stops / Shenmue II

### ISSUE THREAD

**Issue by jra22387** [p1pkin/demul#390]
I have experienced two big issues with the newest build of Demul I wanted to make known.  

1. Dynamite Cop is unplayable with a controller input selected.  Once the game loads to the memory card selection the input stops working completely.  

3. Shenmue II does not work with the newest build I have seen.   It loads to the "Now Loading" screen and then bootloops back to the Dreamcast opening logo.

**Comment by p1pkin** [comment]
short answer: reinstall emulator into empty folder with default settings and both mentioned games will work fine.

long answer: no offence, but the main issue - you are changing settings but don't know that they for.
1. happens because you assigned "Extended Controller buttons", there number of games not compatible with such extended controllers. and that's why they do not configured by default.
2. not sure, but I guess something similar - you messed with settings and broke it,

**Comment by jra22387** [comment]
no offense taken, and you're probably right.  I will default them and see how it runs.

Side note, will Demul ever have the Internal Resolution option like there was in the old plugins or is that a long ways out?  At least maybe have the option available even though its not to "Developer" standards?  The option being greyed out is almost like a teaser

Also, any new upcoming releases in the works?

**Comment by jra22387** [comment]
Update:

Re downloaded it and left all default settings and Shenmue II still fails to load.  Dynamite Cop is however fixed.

**Comment by p1pkin** [comment]
Internal Resolution - this feature not present not because some "Dev standards" but because it requires really big amount of work. it was possible as simple hack in older incomplete renderer plugin, but in current renderer such tiny hacks not possible anymore.

ShenmueII - can't reproduce, it works fine here. that disk images you use ?

**Comment by jra22387** [comment]
hmm, I can try a different source to get it from.  Just got it from emuparadise.me.

Looking forward to the upcoming releases and improvements.

**Comment by p1pkin** [comment]
is this still actual ? got Shenmue2 from EP, converted MDF/MDS to CDI, works fine for me...

**Comment by jra22387** [comment]
I got it to work finally, just re downloaded the CDI image.  Was trying to get Dynamite Cop to work online however it keeps giving a data timeout error even though my buddy can directly connect to me without any problem and ping is super low.  Any suggestions on Netplay functions with Demul yet?

**Comment by p1pkin** [comment]
no, dreamcast modem not emulated.
only broadband adapter is emulated, which supported by few games like Quake 3 or Phantasy Star Online

if you meant kaillera netplay - fast connection with low latency required, like LAN or equivalent.
