### ISSUE TITLE
Netplay w Kaillera?

### ISSUE THREAD

**Issue by jra22387** [p1pkin/demul#396]
I noticed the newest build has Kaillera capabilities, however when you start a room and load a game...the game never loads.  Will this be fixed in the future releases?  Would be nice to play online again (I seen reports of the older version working at one point).  Thanks for your hard work.

**Comment by p1pkin** [comment]
newer versions have automatic non-volatile data synchronization (ie Dreamcast flash or NAOMI SRAM, etc) over Kaillera. but since Kailera originally not intended to send any data over it - it require very low latency connection, otherwise data sync take very long time (half of hour easy).

in next release this will be an option, so people with high latency connection will be able to disable this feature, and will sync nvram/* manually.
