### ISSUE TITLE
Capcom vs SNK 2 sprite glitch.

### ISSUE THREAD

**Issue by Enio-Perceval** [p1pkin/demul#450]
I have all Naomi games running graphicly fine with gpuDX11old in 3x internal resolution, but Capcom vs SNK 2 is a problem. When using gpuDX11old in any internal resolution, the characters sprites starts to ramdomly get broken. It's fixed whe usin the new gpuDX11 but, because I can only play in 1x internal resolution, the 3D stages look ugly as hell. Can it be fixed in future to work in different internal resolutions without this graphical glitch? As I said, it's the only game I have problem. Everything else runs just fine.

I'm using a Zotac GTX 1060 Amp Plus 6gb graphic card.

Thanks a lot and
![cvs2 glitch](https://user-images.githubusercontent.com/36431124/36132122-8e5caa96-105c-11e8-81ab-0d194fbb8496.jpg)
 cheers from Brazil.

Enio.

**Comment by Enio-Perceval** [comment]
Funny thing is: Marvel vs Capcom 2 has basically the same composition as Capcom vs SNK 2: 2D sprites with 3D backgrounds, but I don't have any kind of graphical problem with this game (only a strange and spooky inifinte sound feedbacs from Doctor Doom and Anakaris).

**Comment by p1pkin** [comment]
> When using gpuDX11old in any internal resolution, the characters sprites starts to ramdomly get broken

right, and that's one of reasons why modern gpuDX11 was created - by it's design old renderer is not capable to work with 2D sprite games normally, and produced artifacts like in this game, or massive slowdowns like it MetalSlug6 or crashes after some play time.

this was fixed by creating modern gpuDX11, and one of main reasons why it exists.

**Comment by Enio-Perceval** [comment]
Thanks for you reply p1pkin (it was really fast!). It will be possible, in future, tu play with modern gpuDX11 with bigger internal resolutions? Demul is the only emulator I really play nowdays. I really love it, that's why a ask about the internal resolution thing. Anyway, are you it's creator?! Would be very nice to know someone who created something I play everyday!

Nice to meet you and thanks for you reply.

**Comment by p1pkin** [comment]
yes, I'm developer.

no, its almost impossible to implement hires render in gpuDX11, because gpuDX11 renderer works in mostly same way as original Dreamcast/NAOMI hardware, and as result have same limitations as original hardware. i.e. not capable of doing hires render or output.

for hires render and other similar stuff there is plans to make dirty hacky HLE-ish renderer, to make all emukiddies happy it looks nice and smooth, and nowhere close to real thing :) but do not expect it happen any soon.
