### ISSUE TITLE
Monkey Ball 

### ISSUE THREAD

**Issue by LasagnaPie** [p1pkin/demul#452]
I have Monkey Ball but unable to launch it through command-line'

-run=naomi -rom="E:\ROMs\Sega Naomi\monkey_ball.dat"  

I tried this, but doesn't work, instead it goes too the 'select rom' interface,  however Monkey Ball isn't even listed,  but the game does work with 'lord encrypted rom' ( but not when compressed in a zip folder).

**Comment by p1pkin** [comment]
why not try "demul.exe /?" and read short description ?
for decrypted hacky crap should be used "-customrom=" option.
speaking in general, "load decrypted" doesn't recommended to be used to play the games, because in this case number of features will be missing - no automatic screen orientation switch, no auto player number setup, no specific input mapping or special IO-boards simulation, etc.
this feature mainly exist for me and fellows who use Demul to test hacks made by themselves ;)
