### ISSUE TITLE
Yet another OSS request

### ISSUE THREAD

**Issue by Guy1524** [p1pkin/demul#474]
I'm sure you've had a million of these and you are tired of them, but I have recently done some work in porting DXVK, a popular D3D11 -> Vulkan layer, to a native linux library.  Using this, I would like to port a popular d3d application to Linux for fun/learning.  While trying to find a suitable open source d3d application, I remembered this emulator being mentioned in the DXVK issue tracker, but then I found out that it is closed source.

So my question is, do you have any plans on open-sourcing this in the future, I would love to try and port this application to Linux.

**Comment by p1pkin** [comment]
currently there is no plans.
also it might be not easy, because there will be required permission of every developer involved in Demul project during all >10years, to relicense theirs intellectual property (code) under some FOSS license.

**Comment by Guy1524** [comment]
Ah, I see.  Thanks for the information.

**Comment by SpiralBrad** [comment]
> currently there is no plans. also it might be not easy, because there will be required permission of every developer involved in Demul project during all >10years, to relicense theirs intellectual property (code) under some FOSS license.

I have a hard time believing contributors' code was submitted to the project to explicitly be licensed as closed source; unless licenses were attached to submissions, the code is likely 'owned' by the maintainers to do with as you/they wish.

And now the project has stalled for 4 years, because that's what happens to closed source projects.  Awesome.

**Comment by p1pkin** [comment]
@SpiralBrad 
> And now the project has stalled for 4 years,

it's not, project still in active research and development, even today. it's just current maintainer(s) not cared to make public builds.

> that's what happens to closed source projects. Awesome.

please, stop it, in return I may provide veeeery loooong list of FOSS emulation projects with zero progress and no any "3rd-party" devs interest during many years.
IMHO open source approach works very very bad for emulation projects, it almost doesn't work at all. except for very few projects, which basically can be counted using only fingers.

**Comment by SpiralBrad** [comment]
@p1pkin 

> > And now the project has stalled for 4 years,
> 
> it's not, project still in active research and development, even today. it's just current maintainer(s) not cared to make public builds.

No releases or even the tiniest of updates in 4 years; I wonder why someone would think this?  Also, prove it, cuz otherwise it's just words.

No public builds in 4 years despite claimed active development (and hopefully improvement), yet locked to only some scant minority of private devs? ...fkn why?

> > that's what happens to closed source projects. Awesome.
> 
> please, stop it

Nah, I don't think I will.

> in return I may provide veeeery loooong list of FOSS emulation projects with zero progress

Ooh a cherry picking game.  Fun, but pointless.

> IMHO open source approach works very very bad for emulation projects, it almost doesn't work at all. except for very few projects, which basically can be counted using only fingers.

IMHO you're wrong.

**Comment by p1pkin** [comment]
@SpiralBrad 

> No releases or even the tiniest of updates in 4 years; I wonder why someone would think this? Also, prove it, cuz otherwise it's just words.

people who really interested knows my YT channel, where posted videos with new platforms or games research and emulation progress.

> No public builds in 4 years despite claimed active development (and hopefully improvement), yet locked to only some scant minority of private devs? ...fkn why?

because for example for me it is mainly research project for personal fun. creating some tool for other people to play teh games not a main goal, never was.

**Comment by p1pkin** [comment]
@SpiralBrad 
> IMHO you're wrong.

code you see in this repo originally was published at sourceforge back in mid 2000x, but during 10+ years nobody was cared to join it's development.
how do you explain this ?

**Comment by SpiralBrad** [comment]
@p1pkin
> it is mainly research project for personal fun. creating some tool for other people to play teh games not a main goal, never was.

Great, so the purpose of prior public releases and continuing to maintain a public site/github, YouTube channel, etc... is what exactly?  Seems incongruous.

> code you see in this repo originally was published at sourceforge back in mid 2000x, but during 10+ years nobody was cared to join it's development. how do you explain this ?

You think I can read minds?  Why have people cared TO join other, open source projects?  I'd posit that neither of us can answer that, either.

**Comment by awsms** [comment]
>please, stop it, in return I may provide veeeery loooong list of FOSS emulation projects with zero progress and no any "3rd-party" devs interest during many years.
IMHO open source approach works very very bad for emulation projects, it almost doesn't work at all. except for very few projects, which basically can be counted using only fingers.

dude ur emulator is literal abandonware, while cemu got a hundreed of contributors when it was opensourced
